### PR TITLE
update :: login/register style & layout

### PR DESCRIPTION
**Pull request by erdemuslu**

### CODE REVIEW

**Comment by ayushagg31** [comment]
Thanks @erdemuslu, it looks good but there's one issue. Alert messages are not aligned anymore, please look into this issue. 
image
**Expected Behaviour** - Alert messages should be displayed on top of the form.

**Comment by erdemuslu** [comment]
Hi @ayushagg31, I fixed it.

**Comment by ayushagg31** [comment]
Thanks @erdemuslu, this looks good, but there're still some issues which I didn't notice the last time, I see you have increased the height of header, now it's collapsing with some buttons inside boards, please try to fix them as well. Attaching few snips below from your version.
image
image

**Comment by erdemuslu** [comment]
@ayushagg31 Can you open another issue for this? So you can merge the login/register section.

**Comment by ayushagg31** [comment]
I'm not sure whether or not I understand it. Can you tell me why exactly you want to raise new issue?

**Pull request closed without merging**
