### PR TITLE
Updating readme files with correct command

### LINKED ISSUE #31: Fixing typo in readme files
### Overview Description
# Steps to Reproduce

1. Open README or CONTRIBUTING.
2. Scroll to the section explaining how to make a dev.env for development.
3. Wrong command specified.

# Actual Results
`mkdir dev.env` - which will create a directory.

# Expected Results
`touch dev.env` - which will create a file.

# Additional Information:
Have also added an `echo` command to populate the file.

### PR DESCRIPTION
**Pull request by jacubsmith**
### Overview Description
Changing command to create the dev.env file and adding echo to populate it for ease of use. Have chosen master as merge branch to keep up to date with README changes.

# Issue Reference: 
closes #31 

# Changes
Change `mkdir` to `touch`.

# Expected Outcome
Create a file and not a directory

### CODE REVIEW

**Comment by ayushagg31** [comment]
Thanks @jacubsmith for pointing out this mistake, although `touch` is a Linux specific command, so please create instruction for both windows and Linux seperately.

## Windows
```
cd ../config 
(
echo PORT=1313
echo DATABASE_URL="MongoDB Connection String"
echo JWT_SECRET="YOUR JWT TOKEN"
echo NODE_ENV=development
) > dev.env
```

**Comment by jacubsmith** [comment]
@ayushagg31 thanks for pointing that out, I'll update the PR for you this evening

**Comment by jacubsmith** [comment]
> Windows

Have tested this command on my machine (macOS) and it works fine so have used it for both.

**Comment by ayushagg31** [comment]
Great.

**Review by ayushagg31 — APPROVED** [review]

**Pull request merged**
