### PR TITLE
#18 Responsive website

### PR DESCRIPTION
**Pull request by dfoltynski**

### CODE REVIEW

**Comment by ayushagg31** [comment]
- Thanks @dfoltynski for submitting this PR. Can you provide info about what all the changes have you done and their expected outcome. 
- Issues I found while reviewing, Login and Register Button are missing from header section in your changes. Please look into this issue.

**Comment by dfoltynski** [comment]
> * Thanks @dfoltynski for submitting this PR. Can you provide info about what all the changes have you done and their expected outcome.
> * Issues I found while reviewing, Login and Register Button are missing from header section in your changes. Please look into this issue.

Yesterday I rewrite your buttons to behave properly, make them responsive, also I have made your Header, Cards, Boards, Footer and everything else responsive 😊

I repaired those issues, but imo there is a big problem with making it responsive with your Auth wrapper for Login and Register button, I tried my best, if there is sth wrong tell me 😊

**Comment by ayushagg31** [comment]
Thanks for the update, I'll be reviewing it soon

**Comment by ayushagg31** [comment]
Can you update your PR or maybe create new one with new master, I have done some major changes and there's a lot of merge conflicts due to linter.

**Pull request closed without merging**
